---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec
  format: progress
  
platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[auto-patch::default]
    attributes:
      auto-patch:
        hour: 9
        minute: 25
        monthly: 'third saturday'
  - name: update-now
    run_list:
      - recipe[auto-patch::update_now]
    attributes:
      auto-patch:
        now: true
        once: true
  - name: once
    run_list:
      - recipe[auto-patch::default]
    attributes:
      auto-patch:
        once: true
        month: 9
        day: 16
        hour: 1
        minute: 00