---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[auto-patch::default]
    attributes:
      auto-patch:
        hour: 9
        minute: 25
        monthly: 'third saturday'
  - name: update-now
    run_list:
      - recipe[auto-patch::update_now]
    attributes:
      auto-patch:
        now: true
        once: true
