AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
  Exclude:
    - test/**/*
    - vendor/**/*
    - ruby/**/*

Style/ConditionalAssignment:
  Exclude:
    - 'libraries/auto_patch.rb'

Metrics/AbcSize:
  Max: 18

AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
